In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, MinMaxScaler

In [20]:
# Loading the dataset to df variable
df = pd.read_csv('../../Data/raw_data/HR-Employee-Attrition.csv')
print("Dataset import successful!")

Dataset import successful!

In [21]:
# View dataset
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

In [22]:
print("Shape: ", df.shape)

Shape:  (1470, 35)

In [23]:
df.duplicated().any()

np.False_

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 402.1 KB

In [25]:
# Set the max rows and columns to display
pd.options.display.max_rows = len(df)
pd.options.display.max_columns = len(df.columns)

In [31]:
df.describe(include='all')

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470,1470,1470,1470.000000,1470.000000,1470,1470.000000,1470.000000,1470,1470.000000,1470.000000,1470,1470.000000,1470,1470.000000,1470.000000,1470,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
unique,NaN,2,3,3,NaN,NaN,6,NaN,NaN,2,NaN,NaN,9,NaN,3,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,No,Travel_Rarely,Research & Development,NaN,NaN,Life Sciences,NaN,NaN,Male,NaN,NaN,Sales Executive,NaN,Married,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1233,1043,961,NaN,NaN,606,NaN,NaN,882,NaN,NaN,326,NaN,673,NaN,NaN,1054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,36.923810,NaN,NaN,NaN,9.192517,2.912925,NaN,1024.865306,2.721769,NaN,2.729932,2.063946,NaN,2.728571,NaN,6502.931293,2.693197,NaN,15.209524,3.153741,2.712245,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,NaN,NaN,NaN,8.106864,1.024165,NaN,602.024335,1.093082,NaN,0.711561,1.106940,NaN,1.102846,NaN,4707.956783,2.498009,NaN,3.659938,0.360824,1.081209,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,NaN,NaN,NaN,1.000000,1.000000,NaN,1.000000,1.000000,NaN,1.000000,1.000000,NaN,1.000000,NaN,1009.000000,0.000000,NaN,11.000000,3.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,NaN,NaN,NaN,2.000000,2.000000,NaN,491.250000,2.000000,NaN,2.000000,1.000000,NaN,2.000000,NaN,2911.000000,1.000000,NaN,12.000000,3.000000,2.000000,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,NaN,NaN,NaN,7.000000,3.000000,NaN,1020.500000,3.000000,NaN,3.000000,2.000000,NaN,3.000000,NaN,4919.000000,2.000000,NaN,14.000000,3.000000,3.000000,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,NaN,NaN,NaN,14.000000,4.000000,NaN,1555.750000,4.000000,NaN,3.000000,3.000000,NaN,4.000000,NaN,8379.000000,4.000000,NaN,18.000000,3.000000,4.000000,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,NaN,NaN,NaN,29.000000,5.000000,NaN,2068.000000,4.000000,NaN,4.000000,5.000000,NaN,4.000000,NaN,19999.000000,9.000000,NaN,25.000000,4.000000,4.000000,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [27]:
df.drop(columns=["EmployeeCount", "StandardHours", "Over18", "DailyRate", "HourlyRate", "MonthlyRate"], inplace=True)

In [32]:
df.head(5)

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,Sales,1,2,Life Sciences,1,2,Female,3,2,Sales Executive,4,Single,5993,8,Yes,11,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,Research & Development,8,1,Life Sciences,2,3,Male,2,2,Research Scientist,2,Married,5130,1,No,23,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,Research & Development,2,2,Other,4,4,Male,2,1,Laboratory Technician,3,Single,2090,6,Yes,15,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,Research & Development,3,4,Life Sciences,5,4,Female,3,1,Research Scientist,3,Married,2909,1,Yes,11,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,Research & Development,2,1,Medical,7,1,Male,3,1,Laboratory Technician,2,Married,3468,9,No,12,3,4,1,6,3,3,2,2,2,2

In [35]:
binary_cols = ['Gender', 'OverTime', 'Attrition']
le  = LabelEncoder()
for col in binary_cols:
    # Chuyển đổi: YES/NO -> 1/0, MALE/FEMALE -> 1/0
    df[col] = le.fit_transform(df[col])

In [38]:
nominal_cols = ['Department', 'EducationField', 'JobRole', 'MaritalStatus']
df = pd.get_dummies(df, columns=nominal_cols, dtype=int)
df.head(5)

,Age,Attrition,BusinessTravel,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,...,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree,JobRole_Healthcare Representative,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single
0,41,1,Travel_Rarely,1,2,1,2,0,3,2,4,5993,8,1,11,3,1,...,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
1,49,0,Travel_Frequently,8,1,2,3,1,2,2,2,5130,1,0,23,4,4,...,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
2,37,1,Travel_Rarely,2,2,4,4,1,2,1,3,2090,6,1,15,3,2,...,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1
3,33,0,Travel_Frequently,3,4,5,4,0,3,1,3,2909,1,1,11,3,3,...,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
4,27,0,Travel_Rarely,2,1,7,1,1,3,1,2,3468,9,0,12,3,4,...,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0

In [39]:
scaler = MinMaxScaler()
scaler_cols = [
    'Age', 'DistanceFromHome','MonthlyIncome', 'NumCompaniesWorked', 
    'PercentSalaryHike', 'TotalWorkingYears', 'TrainingTimesLastYear', 
    'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 
    'YearsWithCurrManager'
]
df[scaler_cols] = scaler.fit_transform(df[scaler_cols])
df.head(5)

,Age,Attrition,BusinessTravel,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,...,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree,JobRole_Healthcare Representative,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single
0,0.547619,1,Travel_Rarely,0.000000,2,1,2,0,3,2,4,0.262454,0.888889,1,0.000000,3,1,...,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
1,0.738095,0,Travel_Frequently,0.250000,1,2,3,1,2,2,2,0.217009,0.111111,0,0.857143,4,4,...,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
2,0.452381,1,Travel_Rarely,0.035714,2,4,4,1,2,1,3,0.056925,0.666667,1,0.285714,3,2,...,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1
3,0.357143,0,Travel_Frequently,0.071429,4,5,4,0,3,1,3,0.100053,0.111111,1,0.000000,3,3,...,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
4,0.214286,0,Travel_Rarely,0.035714,1,7,1,1,3,1,2,0.129489,1.000000,0,0.071429,3,4,...,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0

In [40]:
scaler1_cols = [
    'Education', 'EnvironmentSatisfaction', 'JobInvolvement', 
    'JobLevel', 'JobSatisfaction', 'PerformanceRating', 
    'RelationshipSatisfaction', 'StockOptionLevel', 'WorkLifeBalance'
]
df[scaler1_cols] = scaler.fit_transform(df[scaler1_cols])
df.head(5)

,Age,Attrition,BusinessTravel,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,...,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree,JobRole_Healthcare Representative,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single
0,0.547619,1,Travel_Rarely,0.000000,0.25,1,0.333333,0,0.666667,0.25,1.000000,0.262454,0.888889,1,0.000000,0.0,0.000000,...,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
1,0.738095,0,Travel_Frequently,0.250000,0.00,2,0.666667,1,0.333333,0.25,0.333333,0.217009,0.111111,0,0.857143,1.0,1.000000,...,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
2,0.452381,1,Travel_Rarely,0.035714,0.25,4,1.000000,1,0.333333,0.00,0.666667,0.056925,0.666667,1,0.285714,0.0,0.333333,...,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1
3,0.357143,0,Travel_Frequently,0.071429,0.75,5,1.000000,0,0.666667,0.00,0.666667,0.100053,0.111111,1,0.000000,0.0,0.666667,...,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
4,0.214286,0,Travel_Rarely,0.035714,0.00,7,0.000000,1,0.666667,0.00,0.333333,0.129489,1.000000,0,0.071429,0.0,1.000000,...,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0

In [41]:
#Chuyển thành dạng 0 1 2
travel_map = {
    'Non-Travel': 0,
    'Travel_Rarely': 1,
    'Travel_Frequently': 2
}
df['BusinessTravel'] = df['BusinessTravel'].map(travel_map)
df.head(5)

,Age,Attrition,BusinessTravel,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,...,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree,JobRole_Healthcare Representative,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single
0,0.547619,1,1,0.000000,0.25,1,0.333333,0,0.666667,0.25,1.000000,0.262454,0.888889,1,0.000000,0.0,0.000000,...,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
1,0.738095,0,2,0.250000,0.00,2,0.666667,1,0.333333,0.25,0.333333,0.217009,0.111111,0,0.857143,1.0,1.000000,...,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
2,0.452381,1,1,0.035714,0.25,4,1.000000,1,0.333333,0.00,0.666667,0.056925,0.666667,1,0.285714,0.0,0.333333,...,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1
3,0.357143,0,2,0.071429,0.75,5,1.000000,0,0.666667,0.00,0.666667,0.100053,0.111111,1,0.000000,0.0,0.666667,...,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
4,0.214286,0,1,0.035714,0.00,7,0.000000,1,0.666667,0.00,0.333333,0.129489,1.000000,0,0.071429,0.0,1.000000,...,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0

In [45]:
#Chuyển về khoảng cách 0-1
df[['BusinessTravel']] = scaler.fit_transform(df[['BusinessTravel']])
df.head(20)

,Age,Attrition,BusinessTravel,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,...,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree,JobRole_Healthcare Representative,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single
0,0.547619,1,0.5,0.000000,0.25,1,0.333333,0,0.666667,0.25,1.000000,0.262454,0.888889,1,0.000000,0.0,0.000000,...,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
1,0.738095,0,1.0,0.250000,0.00,2,0.666667,1,0.333333,0.25,0.333333,0.217009,0.111111,0,0.857143,1.0,1.000000,...,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
2,0.452381,1,0.5,0.035714,0.25,4,1.000000,1,0.333333,0.00,0.666667,0.056925,0.666667,1,0.285714,0.0,0.333333,...,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1
3,0.357143,0,1.0,0.071429,0.75,5,1.000000,0,0.666667,0.00,0.666667,0.100053,0.111111,1,0.000000,0.0,0.666667,...,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
4,0.214286,0,0.5,0.035714,0.00,7,0.000000,1,0.666667,0.00,0.333333,0.129489,1.000000,0,0.071429,0.0,1.000000,...,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0
5,0.333333,0,1.0,0.035714,0.25,8,1.000000,1,0.666667,0.00,1.000000,0.108425,0.000000,0,0.142857,0.0,0.666667,...,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
6,0.976190,0,0.5,0.071429,0.50,10,0.666667,0,1.000000,0.00,0.000000,0.087467,0.444444,1,0.642857,1.0,0.000000,...,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0
7,0.285714,0,0.5,0.821429,0.00,11,1.000000,1,0.666667,0.00,0.666667,0.088678,0.111111,0,0.785714,1.0,0.333333,...,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
8,0.476190,0,1.0,0.785714,0.50,12,1.000000,1,0.333333,0.50,0.666667,0.448499,0.000000,0,0.714286,1.0,0.333333,...,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
9,0.428571,0,0.5,0.928571,0.50,13,0.666667,1,0.666667,0.25,0.666667,0.222643,0.666667,0,0.142857,0.0,0.333333,...,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0
10,0.404762,0,0.5,0.535714,0.50,14,0.000000,1,1.000000,0.00,0.333333,0.074618,0.000000,0,0.142857,0.0,0.666667,...,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0
11,0.261905,0,0.5,0.500000,0.25,15,1.000000,0,0.333333,0.25,0.666667,0.167667,0.000000,1,0.071429,0.0,1.000000,...,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
12,0.309524,0,0.5,0.892857,0.00,16,0.000000,1,0.666667,0.00,0.666667,0.100158,0.111111,0,0.428571,0.0,1.000000,...,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0
13,0.380952,0,0.5,0.642857,0.25,18,0.333333,1,0.666667,0.00,1.000000,0.086993,0.000000,0,0.000000,0.0,0.666667,...,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0
14,0.238095,1,0.5,0.821429,0.50,19,0.666667,1,0.333333,0.00,0.666667,0.053660,0.555556,1,0.214286,0.0,0.333333,...,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
15,0.261905,0,0.5,0.714286,0.75,20,0.333333,0,1.000000,0.50,0.000000,0.472407,0.111111,0,0.000000,0.0,0.666667,...,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0
16,0.333333,0,0.5,0.142857,0.25,21,0.000000,1,1.000000,0.00,0.333333,0.120537,0.000000,1,0.071429,0.0,1.000000,...,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0
17,0.095238,0,0.0,0.535714,0.25,22,1.000000,1,1.000000,0.00,1.000000,0.101422,0.111111,1,0.142857,0.0,0.333333,...,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0
18,0.833333,0,0.5,0.035714,0.75,23,0.000000,0,0.333333,0.75,1.000000,0.759242,0.222222,0,0.357143,0.0,0.666667,...,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0
19,0.476190,0,0.5,0.035714,0.50,24,1.000000,1,0.666667,0.00,1.000000,0.154555,0.555556,1,0.000000,0.0,0.666667,...,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1

In [50]:
# Lưu dữ liệu đã tiền xử lý
df.to_csv('../../Data/processed_data/HR-Employee-Attrition-Processed.csv', index=False)

print("Lưu thành công")

Lưu thành công